name: Telegram ChatGPT Bot

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/10 * * * *'  # Cứ 10 phút restart 1 lần

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 354  # gần 6 tiếng - giới hạn GitHub Free
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py
